### ISSUE TITLE
Elegoo Mars 5 Ultra compatibility ?

### ISSUE THREAD

**Issue by jeroenwalter** [jeroenwalter/SdcpMonitor#5]
I'd like to know if the Mars 5 Ultra is compatible with SdcpMonitor.
I think it should be, but I don't have a Mars 5 Ultra.
If someone has one, please test this out and leave some feedback.

**Comment by dhoward86** [comment]
This is my M5U.  Working great
![image](https://github.com/user-attachments/assets/a9e032c4-e7ae-4051-b229-4a968e95374b)

**Comment by jeroenwalter** [comment]
Awesome !
